### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

### merging parameters
delta_prior1_ckpt: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
delta_prior2_ckpt: null
delta_prior_include_bias: true
delta_prior_scale: adaptive_cosine
delta_prior_merge_patterns: null
delta_prior_alpha: null
delta_prior_only_layers: null
delta_prior_skip_first_n: 0
delta_prior_normalize_delta_to_param: true


### dataset
dataset: DRIFT-TL-Distill-4K
template: qwen2_vl
cutoff_len: 32768
max_samples: 10000 
overwrite_cache: true
preprocessing_num_workers: 128
dataloader_num_workers: 4

### output
output_dir: drift_default_qwen2_5vl_full_sft_merge
logging_steps: 10
save_steps: 2000
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
# gradient_checkpointing: true
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
val_size: 0
per_device_eval_batch_size: 1
eval_strategy: 'no'
eval_steps: 10000000

###tokenizer
add_tokens: <think>,</think>
skip_special_tokens: false
resize_vocab: true